FROM python:3.7.3

WORKDIR /app

# Install necessary dependencies
RUN pip install --no-cache-dir junit-xml xmlrunner

# Copy your application code and test data
COPY test_main.py .
COPY movies.json .

# Set the command to run your tests
CMD ["python", "test_main.py"]
