FROM python:3.7.3

# Install Git
RUN apt-get update && apt-get install -y git

WORKDIR /app

# Install unittest-xml-reporting from GitHub
RUN pip install git+https://github.com/xmlrunner/unittest-xml-reporting.git

COPY test_main.py .
COPY movies.json .
CMD python test_main.py
